builders: add a check for expired key (PROJQUAY-3489)
This fixes the crash:

DataError: Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.

This is happening because we access a value of a key which has expired